name: newserverdemo
description: A new Flutter application.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1
  at_demo_data: ^0.0.2
  cupertino_icons: ^0.1.3
  modal_progress_hud: any
  at_client_mobile: ^1.0.0
  atsign_authentication_helper:
    git:
      url: git@github.com:atsign-foundation/at_widgets.git
      path: atsign_authentication_helper
      ref: dev_env

#dev_dependencies:
#  flutter_test:
#    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/atsign_logo.png