name: at_chat_flutter_example
description: Welcome to our SB Hacks workshop session! This app
  demonstrates how to use the at_chat_flutter plugin.
version: 0.0.1
homepage: https://atsign.com/

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  atsign_authentication_helper: ^0.0.2
  modal_progress_hud: any
  marquee_widget: ^1.0.0
  at_chat_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets.git
      path: at_chat_flutter
      ref: dev_env
  at_demo_data:
    git:
      url: https://github.com/atsign-foundation/at_demos.git
      path: at_demo_data
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
